grafana image renderer service
opentelekomcloud-infra/ansible-role-grafana pull request #2
Opened 2020-07-06 12:29 UTC by kucerakk

Separate Grafana image renderer service for Grafana 7

2020-07-06 12:57 UTC, gtema requested changes

2020-07-06 12:57 UTC, gtema commented on tasks/main.yml
> +- name: Write Grafana Image Renderer Systemd unit file
let's make this step optional to let deploy grafana without renderer or deploy one renderer with multiple grafana instances

2020-07-08 07:44 UTC, kucerakk commented on tasks/main.yml
> +- name: Write Grafana Image Renderer Systemd unit file
when: grafana_enable_renderer

2020-07-08 08:17 UTC, gtema approved these changes

2020-07-08 08:17 UTC, merged